// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Electrified (electrifiedtrading)

//@version=4
study(title='Moving Average Weighted, Volume Adjusted', shorttitle='VAWMA', overlay=true, resolution='')

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// VAWMA = VWMA and WMA combined.
// Simply put, this attempts to determine the average price per share over time weighted heavier for recent values.
// Uses triangular algorithm to taper off values in the past (same as WMA does).
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

src    = input(hlc3, title='Source')
len    = input(50, minval=1, title='Length')

sum = 0.0
vol = 0.0
for m = 1 to len // m = triangular multiple
    i = len - m
    v = volume[i] * m
    vol := vol + v
    sum := sum + src[i] * v

plot(sum/vol, color=color.purple, title='VAWMA')

